### ISSUE TITLE
activemq.transport property in bot.properties

### ISSUE THREAD

**Issue by maoo** [symphonyoss/vote-bot#3]
In `bot.properties` I see that `activemq.transport=tcp://localhost:61616` is defined; however, if I search for `activemq.transport` in the codebase I cannot find any other occurrence.

Is this property used and - therefore - it needs an ActiveMQ running, or it's not used and we can get rid of it?

**Comment by ftbb** [comment]
commit 125707711dc3e2148f4f7c2299cfb83679b78a16

Removed
