### ISSUE TITLE
Remove confidential information from publicly committed src/main/config/bot.properties

### ISSUE THREAD

**Issue by mindthegab** [symphonyoss/vote-bot#5]
https://github.com/symphonyoss/vote-bot/blob/develop/vote-bot-service/src/main/config/bot.properties has confidential information publicly committed. 

Since it's already extrapolated properties, can we leave a dummy default committed for testing purpose while we can add the actual configuration in externalized runtime properties (e.g. ENV variables) that are not committed in the repo?

@maoo can probably help here.

**Comment by ftbb** [comment]
commit de6c2a04785ac4cdd2e04f547e1971634c56497b

Removed values.

The properties can be resourced through ENV variables already.  (Almost all by the way)

see: 
https://github.com/symphonyoss/vote-bot/blob/develop/vote-bot-service/src/main/java/org/symphonyoss/vb/config/BotConfig.java
